version: "3.8"

services:
  backend:
    build: ./Server
    container_name: insurance_backend
    ports:
      - "8282:8282"
    environment:
      - PORT=8282
      - MONGO_URI=mongodb://mongo:27017/insurance_db
    depends_on:
      - mongo
    restart: always

  frontend:
    build: ./FrontEnd/insurance_app
    container_name: insurance_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8282
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:6
    container_name: insurance_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data: